# Generated by Django 4.1.6 on 2023-03-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField()),
                ('donation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('uses', models.IntegerField(default=0)),
            ],
        ),
    ]
