# Generated by Django 4.1.7 on 2023-03-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodbank',
            name='donation_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='foodbank',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
